---
- name: Run Docker commands to update containers
  hosts: localhost
  become: yes  # Ensure you're running as root or with sudo
  tasks:

    - name: Run Docker pull images
      ansible.builtin.command:
        chdir: /WebServer/traefik/
        cmd: docker compose pull

    - name: Run Docker compose down
      ansible.builtin.command:
      chdir: /WebServer/traefik/
      cmd: docker compose down

    - name: Run Docker compose
      ansible.builtin.command:
        chdir: /WebServer/traefik/
        cmd: docker compose up -d