---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
   - ca-certificates
   - curl
   - apt-transport-https

- name: Create dir with permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download docker gpg key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Ensure /etc/apt/sources.list.d/ directory exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/
    state: directory
    mode: '0755'

- name: Set architecture variable
  set_fact:
    docker_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

- name: somerepo | apt source
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
  
- name: Update apt cache
  apt:
    update_cache: yes
  
- name: Install the Docker packages.
  apt:
    name: "{{ item }}"
    state: present
  loop:
   - docker-ce
   - docker-ce-cli
   - containerd.io
   - docker-buildx-plugin
   - docker-compose-plugin

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes